package cli

import (
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestUpsertConfKey_ReplaceExisting(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "cfm.conf")
	original := "# cfm.conf\nFOO = 1\nCLAMD_ENABLED = true\nBAR = 2\n"
	if err := os.WriteFile(path, []byte(original), 0640); err != nil {
		t.Fatal(err)
	}

	if err := UpsertConfKey(path, "CLAMD_ENABLED", "false"); err != nil {
		t.Fatalf("UpsertConfKey: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	want := "# cfm.conf\nFOO = 1\nCLAMD_ENABLED = false\nBAR = 2\n"
	if string(got) != want {
		t.Errorf("content drift\n got: %q\nwant: %q", got, want)
	}

	// Mode preserved.
	fi, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if fi.Mode().Perm() != 0640 {
		t.Errorf("mode drift: got %04o want 0640", fi.Mode().Perm())
	}

	// No leftover .tmp from the atomic-rename path.
	if _, err := os.Stat(path + ".tmp"); !os.IsNotExist(err) {
		t.Errorf("leftover tmp file present (err=%v)", err)
	}
}

func TestUpsertConfKey_AppendWhenAbsent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "cfm.conf")
	if err := os.WriteFile(path, []byte("FOO = 1\n"), 0640); err != nil {
		t.Fatal(err)
	}

	if err := UpsertConfKey(path, "CLAMD_NGINX_HOOK_ENABLED", "false"); err != nil {
		t.Fatalf("UpsertConfKey: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(got), "CLAMD_NGINX_HOOK_ENABLED = false") {
		t.Errorf("appended key missing in: %q", got)
	}
	if !strings.Contains(string(got), "FOO = 1") {
		t.Errorf("pre-existing key dropped: %q", got)
	}
}

func TestUpsertConfKey_AppendsTrailingNewline(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "cfm.conf")
	// File without trailing newline.
	if err := os.WriteFile(path, []byte("FOO = 1"), 0640); err != nil {
		t.Fatal(err)
	}

	if err := UpsertConfKey(path, "BAR", "true"); err != nil {
		t.Fatalf("UpsertConfKey: %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != "FOO = 1\nBAR = true\n" {
		t.Errorf("got: %q", got)
	}
}

func TestUpsertConfKey_NoOpWhenValueUnchanged(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "cfm.conf")
	original := "CLAMD_ENABLED = true\n"
	if err := os.WriteFile(path, []byte(original), 0640); err != nil {
		t.Fatal(err)
	}
	infoBefore, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}

	if err := UpsertConfKey(path, "CLAMD_ENABLED", "true"); err != nil {
		t.Fatalf("UpsertConfKey: %v", err)
	}

	// Content unchanged.
	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != original {
		t.Errorf("content drift on no-op: %q", got)
	}
	// And no rename happened (mtime unchanged) — proves we short-circuited
	// before the atomic-write path.
	infoAfter, err := os.Stat(path)
	if err != nil {
		t.Fatal(err)
	}
	if !infoBefore.ModTime().Equal(infoAfter.ModTime()) {
		t.Errorf("mtime changed on no-op upsert: before=%s after=%s",
			infoBefore.ModTime(), infoAfter.ModTime())
	}
}

func TestUpsertConfKey_RejectsInvalidKey(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "cfm.conf")
	if err := os.WriteFile(path, []byte(""), 0640); err != nil {
		t.Fatal(err)
	}
	for _, k := range []string{"", "WITH SPACE", "with-dash", "FOO;rm -rf"} {
		if err := UpsertConfKey(path, k, "x"); err == nil {
			t.Errorf("expected error for invalid key %q, got nil", k)
		}
	}
}

func TestUpsertConfKey_RequiresAbsolutePath(t *testing.T) {
	if err := UpsertConfKey("relative.conf", "FOO", "1"); err == nil {
		t.Errorf("expected error for relative path")
	}
}

// TestClamavHookSentinelRE locks the writer/reader contract:
// sslcollector.WriteClamavLuaConfig emits a `-- CFM_HOOK_ENABLED=<bool>`
// header line; clamavHookSentinelRE here must keep parsing it. Both live
// in this repo — if anyone reformats one, this test catches the drift.
func TestClamavHookSentinelRE(t *testing.T) {
	cases := []struct {
		name    string
		input   string
		wantOK  bool
		wantVal string
	}{
		{
			name:    "writer-exact-true",
			input:   "-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit\n-- CFM_HOOK_ENABLED=true\nreturn {\n  enabled = true,\n}\n",
			wantOK:  true,
			wantVal: "true",
		},
		{
			name:    "writer-exact-false",
			input:   "-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit\n-- CFM_HOOK_ENABLED=false\nreturn {\n  enabled = false,\n}\n",
			wantOK:  true,
			wantVal: "false",
		},
		{
			name:    "extra-space-after-dashes",
			input:   "--   CFM_HOOK_ENABLED=true\n",
			wantOK:  true,
			wantVal: "true",
		},
		{
			name:    "trailing-whitespace",
			input:   "-- CFM_HOOK_ENABLED=false   \n",
			wantOK:  true,
			wantVal: "false",
		},
		{
			name:    "must-be-anchored-not-substring",
			input:   "return { note = \"-- CFM_HOOK_ENABLED=true\" }\n",
			wantOK:  false,
			wantVal: "",
		},
		{
			name:    "invalid-value-rejected",
			input:   "-- CFM_HOOK_ENABLED=yes\n",
			wantOK:  false,
			wantVal: "",
		},
		{
			name:    "no-sentinel-at-all",
			input:   "return { enabled = true }\n",
			wantOK:  false,
			wantVal: "",
		},
		{
			name:    "old-format-falls-back-to-unknown",
			input:   "-- AUTO-GENERATED\nreturn { enabled = true }\n",
			wantOK:  false,
			wantVal: "",
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			m := clamavHookSentinelRE.FindStringSubmatch(tc.input)
			gotOK := m != nil
			if gotOK != tc.wantOK {
				t.Fatalf("match ok = %v want %v", gotOK, tc.wantOK)
			}
			if gotOK && m[1] != tc.wantVal {
				t.Errorf("captured %q want %q", m[1], tc.wantVal)
			}
		})
	}
}

// The block/allow callers key valueFlags as "--ttl" / "-r"; the split must
// attach the value whatever spelling the caller or the operator uses.
func TestSplitFlagsAndPositionalsValueFlagSpellings(t *testing.T) {
	for _, keys := range []map[string]bool{
		{"--ttl": true, "-r": true},
		{"ttl": true, "r": true},
	} {
		for _, args := range [][]string{
			{"192.0.2.77", "-r", "why", "--ttl", "10m"},
			{"-ttl", "10m", "192.0.2.77", "--r", "why"},
		} {
			flags, pos := SplitFlagsAndPositionals(args, keys)
			if len(pos) != 1 || pos[0] != "192.0.2.77" {
				t.Fatalf("keys=%v args=%v: positionals %v, want only the IP", keys, args, pos)
			}
			fs := flag.NewFlagSet("block", flag.ContinueOnError)
			r := fs.String("r", "", "")
			ttl := fs.String("ttl", "", "")
			if err := fs.Parse(flags); err != nil {
				t.Fatalf("parse %v: %v", flags, err)
			}
			if *r != "why" || *ttl != "10m" {
				t.Fatalf("keys=%v args=%v: r=%q ttl=%q, want why / 10m", keys, args, *r, *ttl)
			}
		}
	}
}
