package vhostmap

import (
	"bufio"
	"bytes"
	"fmt"
	"net"
	"os"
	"sort"
	"strings"
)

type BuildOptions struct {
	// Optional overrides
	SourcePath string // optional; if empty -> auto-detect
	VarName    string // default: origin_http_ip
	DefaultIP  string // optional; if empty -> auto-detect
}

type BuildResult struct {
	Provider   string
	DefaultIP  string
	EntryCount int
	Content    []byte
}

func BuildNginxMap(opts BuildOptions) (BuildResult, error) {
	varName := strings.TrimSpace(opts.VarName)
	if varName == "" {
		varName = "origin_http_ip"
	}

	defaultIP := strings.TrimSpace(opts.DefaultIP)
	if defaultIP == "" {
		ip, err := DetectDefaultIPv4()
		if err != nil {
			if ip2 := firstGlobalIPv4(); ip2 != "" {
				defaultIP = ip2
			} else {
				return BuildResult{}, fmt.Errorf("vhostmap: cannot detect default IPv4: %w", err)
			}
		} else {
			defaultIP = ip
		}
	}

	// auto-detect provider
	src := strings.TrimSpace(opts.SourcePath)
	provider := "none"
	hostToIP := map[string]string{}

	if src == "" {
		if fileExists("/etc/userdatadomains") {
			src = "/etc/userdatadomains"
		}
	}

	if src != "" && fileExists(src) {
		m, err := parseCpanelUserDataDomains(src)
		if err != nil {
			return BuildResult{}, err
		}
		if len(m) > 0 {
			provider = "cPanel:" + src
			hostToIP = m
		}
	}

	content := renderNginxMap(varName, defaultIP, provider, hostToIP)
	return BuildResult{
		Provider:   provider,
		DefaultIP:  defaultIP,
		EntryCount: len(hostToIP),
		Content:    content,
	}, nil
}

func parseCpanelUserDataDomains(path string) (map[string]string, error) {
	// Format:
	// domain.tld: user==owner==type==mainDomain==docroot==IP:80==IP:443====...
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()

	out := map[string]string{}
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := strings.TrimSpace(sc.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		parts := strings.SplitN(line, ":", 2)
		if len(parts) != 2 {
			continue
		}
		host := strings.ToLower(strings.TrimSpace(parts[0]))
		payload := strings.TrimSpace(parts[1])
		cols := strings.Split(payload, "==")
		if len(cols) < 6 {
			continue
		}
		ip80 := strings.TrimSpace(cols[5]) // "157.90.128.201:80"
		h, _, err := net.SplitHostPort(ip80)
		if err != nil {
			continue
		}
		if h != "" {
			out[host] = h
		}
	}
	if err := sc.Err(); err != nil {
		return nil, err
	}
	return out, nil
}

func renderNginxMap(varName, defaultIP, provider string, hostToIP map[string]string) []byte {
	var b bytes.Buffer
	fmt.Fprintf(&b, "# AUTOGENERATED - DO NOT EDIT\n")
	fmt.Fprintf(&b, "# source=%s\n", provider)
	fmt.Fprintf(&b, "map $host $%s {\n", varName)
	fmt.Fprintf(&b, "  default %s;\n", defaultIP)

	if len(hostToIP) > 0 {
		hosts := make([]string, 0, len(hostToIP))
		for h := range hostToIP {
			hosts = append(hosts, h)
		}
		sort.Strings(hosts)
		for _, h := range hosts {
			fmt.Fprintf(&b, "  %s %s;\n", h, hostToIP[h])
		}
	}
	fmt.Fprintf(&b, "}\n")
	return b.Bytes()
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}
