package sslcollector

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"regexp"
	"strings"
)

// badTokens matches well-known placeholder values that must not be used in
// production. The check is case-insensitive and requires a full-string match.
var badTokens = regexp.MustCompile(`(?i)^(supersecret|changeme|secret|password|default|token|test|demo|placeholder)$`)

// confTokenLine patches the SSLCOLLECTOR_SOCK_TOKEN line in a cfm.conf file.
var confTokenLine = regexp.MustCompile(`(?m)^(SSLCOLLECTOR_SOCK_TOKEN\s*=\s*).*$`)

// ValidateOrGenerateToken returns current unchanged if it is strong (≥32 chars,
// not a known placeholder). Otherwise it generates a new 48-hex-char token,
// patches the SSLCOLLECTOR_SOCK_TOKEN line in cfgPath in place, and returns the
// new token.
//
// cfgPath may be empty; in that case the file-patch step is skipped (non-fatal)
// and the new token is still returned so the caller can update in-memory config.
func ValidateOrGenerateToken(cfgPath, current string) (string, error) {
	cur := strings.TrimSpace(current)
	if len(cur) >= 32 && !badTokens.MatchString(cur) {
		return cur, nil
	}

	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("sslcollector: token generation failed: %w", err)
	}
	token := hex.EncodeToString(b) // 48 hex chars

	if cfgPath != "" {
		if data, err := os.ReadFile(cfgPath); err == nil {
			updated := confTokenLine.ReplaceAllString(string(data), "${1}"+token)
			// Write with same permissions the file already has (best-effort).
			info, statErr := os.Stat(cfgPath)
			mode := os.FileMode(0640)
			if statErr == nil {
				mode = info.Mode()
			}
			_ = os.WriteFile(cfgPath, []byte(updated), mode)
		}
	}

	return token, nil
}

// WriteLuaToken atomically writes a Lua module that returns the token string to
// luaPath. The file is created with mode 0640. If cfmGID > 0 the file is
// chowned to root:cfmGID so the OpenResty worker (in the cfm group) can read it.
//
// The generated file looks like:
//
//	-- AUTO-GENERATED by CFM — do not edit
//	return "deadbeef..."
func WriteLuaToken(luaPath, token string, cfmGID int) error {
	content := fmt.Sprintf(
		"-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit\nreturn %q\n",
		token,
	)
	tmp := luaPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0640); err != nil {
		return fmt.Errorf("sslcollector: write lua token tmp: %w", err)
	}
	if cfmGID > 0 {
		_ = os.Chown(tmp, 0, cfmGID)
	}
	if err := os.Rename(tmp, luaPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("sslcollector: rename lua token: %w", err)
	}
	return nil
}
