package sslcollector

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"syscall"
	"testing"
)

func TestWriteLuaTokenMissingParentDir(t *testing.T) {
	t.Parallel()

	luaPath := filepath.Join(t.TempDir(), "missing", "cfm_token.lua")
	err := WriteLuaToken(luaPath, "abc123", 0)
	if err == nil {
		t.Fatalf("expected error for missing parent dir, got nil")
	}
	if !strings.Contains(err.Error(), "missing parent directory") {
		t.Fatalf("expected missing parent directory error, got: %v", err)
	}
	if !strings.Contains(err.Error(), luaPath) {
		t.Fatalf("expected error to include target path %q, got: %v", luaPath, err)
	}
}

func TestWriteLuaTokenSuccessWhenDirExists(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "lua")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	luaPath := filepath.Join(dir, "cfm_token.lua")
	if err := WriteLuaToken(luaPath, "tok123", 0); err != nil {
		t.Fatalf("WriteLuaToken: %v", err)
	}

	data, err := os.ReadFile(luaPath)
	if err != nil {
		t.Fatalf("read file: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, `return "tok123"`) {
		t.Fatalf("unexpected lua token content: %q", got)
	}
}

func TestWriteWebdetectorBridgeConfigContent(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "lua")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	luaPath := filepath.Join(dir, "cfm_bridge_config.lua")

	// clearance_refresh = true, origin keepalive off (the defaults)
	cfg := WebdetectorBridgeConfig{
		ClearanceRefresh: true,
		OriginKeepalive:  false,
		OriginKAIdleSec:  3,
		OriginKAMaxReqs:  1000,
	}
	if err := WriteWebdetectorBridgeConfig(luaPath, cfg, 0); err != nil {
		t.Fatalf("WriteWebdetectorBridgeConfig(defaults): %v", err)
	}
	data, err := os.ReadFile(luaPath)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, "clearance_refresh = true,") {
		t.Fatalf("expected clearance_refresh = true, got: %q", got)
	}
	if !strings.Contains(got, "origin_keepalive = false,") {
		t.Fatalf("expected origin_keepalive = false, got: %q", got)
	}
	if !strings.Contains(got, "origin_ka_idle_sec = 3,") {
		t.Fatalf("expected origin_ka_idle_sec = 3, got: %q", got)
	}
	if !strings.Contains(got, "origin_ka_max_reqs = 1000,") {
		t.Fatalf("expected origin_ka_max_reqs = 1000, got: %q", got)
	}
	if !strings.HasPrefix(got, "-- AUTO-GENERATED by CFM") {
		t.Fatalf("missing auto-generated banner, got: %q", got)
	}

	// flipped values (atomic overwrite)
	cfg = WebdetectorBridgeConfig{
		ClearanceRefresh: false,
		OriginKeepalive:  true,
		OriginKAIdleSec:  2,
		OriginKAMaxReqs:  500,
	}
	if err := WriteWebdetectorBridgeConfig(luaPath, cfg, 0); err != nil {
		t.Fatalf("WriteWebdetectorBridgeConfig(flipped): %v", err)
	}
	data, err = os.ReadFile(luaPath)
	if err != nil {
		t.Fatalf("read after overwrite: %v", err)
	}
	got = string(data)
	if !strings.Contains(got, "clearance_refresh = false,") {
		t.Fatalf("expected clearance_refresh = false, got: %q", got)
	}
	if !strings.Contains(got, "origin_keepalive = true,") {
		t.Fatalf("expected origin_keepalive = true, got: %q", got)
	}
	if !strings.Contains(got, "origin_ka_idle_sec = 2,") {
		t.Fatalf("expected origin_ka_idle_sec = 2, got: %q", got)
	}
	if !strings.Contains(got, "origin_ka_max_reqs = 500,") {
		t.Fatalf("expected origin_ka_max_reqs = 500, got: %q", got)
	}
}

func TestWriteClamavLuaConfigContent(t *testing.T) {
	t.Parallel()

	dir := filepath.Join(t.TempDir(), "lua")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	luaPath := filepath.Join(dir, "cfm_clamav_config.lua")

	// enabled = true
	if err := WriteClamavLuaConfig(luaPath, true, false, 0); err != nil {
		t.Fatalf("WriteClamavLuaConfig(true): %v", err)
	}
	data, err := os.ReadFile(luaPath)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	got := string(data)
	if !strings.Contains(got, "-- CFM_HOOK_ENABLED=true") {
		t.Fatalf("missing sentinel for true, got: %q", got)
	}
	if !strings.Contains(got, "enabled = true,") {
		t.Fatalf("missing lua body for true, got: %q", got)
	}
	if !strings.HasPrefix(got, "-- AUTO-GENERATED by CFM") {
		t.Fatalf("missing auto-generated banner, got: %q", got)
	}

	// enabled = false (atomic overwrite)
	if err := WriteClamavLuaConfig(luaPath, false, false, 0); err != nil {
		t.Fatalf("WriteClamavLuaConfig(false): %v", err)
	}
	data, err = os.ReadFile(luaPath)
	if err != nil {
		t.Fatalf("read after overwrite: %v", err)
	}
	got = string(data)
	if !strings.Contains(got, "-- CFM_HOOK_ENABLED=false") {
		t.Fatalf("missing sentinel for false, got: %q", got)
	}
	if !strings.Contains(got, "enabled = false,") {
		t.Fatalf("missing lua body for false, got: %q", got)
	}
	// Old sentinel must not linger (catches partial-overwrite regressions).
	if strings.Contains(got, "CFM_HOOK_ENABLED=true") {
		t.Fatalf("stale sentinel from previous write present: %q", got)
	}
}

func TestWriteLuaTokenFinalModeAndOwnershipUnchangedBehavior(t *testing.T) {
	t.Parallel()

	dir := t.TempDir()
	luaPath := filepath.Join(dir, "cfm_token.lua")
	if err := WriteLuaToken(luaPath, "tok123", 0); err != nil {
		t.Fatalf("WriteLuaToken: %v", err)
	}

	info, err := os.Stat(luaPath)
	if err != nil {
		t.Fatalf("stat: %v", err)
	}
	if mode := info.Mode().Perm(); mode != 0o640 {
		t.Fatalf("mode mismatch: got %o want %o", mode, 0o640)
	}

	st, ok := info.Sys().(*syscall.Stat_t)
	if !ok {
		t.Fatalf("unexpected stat type %T", info.Sys())
	}
	if int(st.Gid) != os.Getgid() {
		t.Fatalf("gid mismatch: got %d want current gid %d", st.Gid, os.Getgid())
	}
}

func TestWriteLuaTokenToExistingParents(t *testing.T) {
	t.Parallel()

	root := t.TempDir()
	existingDir := filepath.Join(root, "openresty", "lua")
	missingDir := filepath.Join(root, "angie", "lua")
	if err := os.MkdirAll(existingDir, 0o755); err != nil {
		t.Fatalf("mkdir existing: %v", err)
	}

	existingPath := filepath.Join(existingDir, "cfm_bridge_token.lua")
	missingPath := filepath.Join(missingDir, "cfm_bridge_token.lua")
	results := WriteLuaTokenToExistingParents("tok-bridge", 0, existingPath, missingPath, existingPath)
	if len(results) != 2 {
		t.Fatalf("results len mismatch: got %d want 2", len(results))
	}

	var existing LuaTokenWriteResult
	var missing LuaTokenWriteResult
	for _, res := range results {
		if res.Path == existingPath {
			existing = res
		}
		if res.Path == missingPath {
			missing = res
		}
	}
	if !existing.Written || existing.Err != nil || existing.Skipped {
		t.Fatalf("expected existing path to be written, got %#v", existing)
	}
	if !missing.Skipped || missing.Err != nil || missing.Written {
		t.Fatalf("expected missing path to be skipped, got %#v", missing)
	}

	data, err := os.ReadFile(existingPath)
	if err != nil {
		t.Fatalf("read existing path: %v", err)
	}
	if !strings.Contains(string(data), `return "tok-bridge"`) {
		t.Fatalf("unexpected token content: %q", string(data))
	}
}

// ─────────────────────────────────────────────────────────────────────────────
// F55 — token charset: an operator token that cannot be emitted as valid LuaJIT
// (via Go %q) must be treated as weak and regenerated, so cfm_token.lua /
// cfm_bridge_token.lua always compile.
// ─────────────────────────────────────────────────────────────────────────────

// zwsp is U+200B (zero-width space). Go %q renders it as the ​ escape,
// which LuaJIT cannot parse — the F55 trigger. Written as an interpreted string
// literal so the source stays plain ASCII.
const zwsp = "​"

func TestTokenIsLuaSafe(t *testing.T) {
	t.Parallel()
	safe := []string{
		"abcdef0123456789",                   // hex (the generated form)
		"AbC-_.~+/=Xyz012345",                // base64url-ish + punctuation
		strings.Repeat("a", 48),              // long alnum
		"!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~", // every graphical ASCII punct incl. \" and \\
	}
	for _, s := range safe {
		if !tokenIsLuaSafe(s) {
			t.Errorf("tokenIsLuaSafe(%q) = false, want true", s)
		}
	}
	unsafe := []string{
		"abc def",                            // space
		"abc\tdef",                           // tab
		"abc\ndef",                           // newline
		"abc\x00def",                         // NUL
		"abc\x1fdef",                         // control
		"abc\x7fdef",                         // DEL
		"abc" + zwsp + "def",                 // zero-width space (multibyte)
		"abc" + string(rune(0x00e9)) + "def", // é, non-ASCII accented rune
		"abc" + string(rune(0x00a0)) + "def", // non-breaking space
	}
	for _, s := range unsafe {
		if tokenIsLuaSafe(s) {
			t.Errorf("tokenIsLuaSafe(%q) = true, want false", s)
		}
	}
}

func TestValidateOrGenerateTokenRegeneratesLuaUnsafe(t *testing.T) {
	t.Parallel()
	// Strong length (>=32) and not a placeholder, but contains a ZWSP → must be
	// regenerated into a Lua-safe token.
	bad := strings.Repeat("a", 40) + zwsp + strings.Repeat("b", 8)

	got, err := ValidateOrGenerateToken("", bad)
	if err != nil {
		t.Fatalf("ValidateOrGenerateToken: %v", err)
	}
	if got == bad {
		t.Fatalf("Lua-unsafe token returned unchanged; expected regeneration")
	}
	if len(got) < 32 || !tokenIsLuaSafe(got) {
		t.Fatalf("regenerated token not strong+Lua-safe: %q", got)
	}

	// Same guard on the generic key variant (used for OPENRESTY_TOKEN, itself
	// emitted to cfm_bridge_token.lua via %q — manager.go).
	got2, err := ValidateOrGenerateTokenKey("", "OPENRESTY_TOKEN", bad)
	if err != nil {
		t.Fatalf("ValidateOrGenerateTokenKey: %v", err)
	}
	if got2 == bad || len(got2) < 32 || !tokenIsLuaSafe(got2) {
		t.Fatalf("key variant did not regenerate a strong+Lua-safe token: %q", got2)
	}
}

func TestValidateOrGenerateTokenKeepsStrongSafeToken(t *testing.T) {
	t.Parallel()
	strong := strings.Repeat("a1b2c3d4", 6) // 48 chars, Lua-safe, not a placeholder
	got, err := ValidateOrGenerateToken("", strong)
	if err != nil {
		t.Fatalf("ValidateOrGenerateToken: %v", err)
	}
	if got != strong {
		t.Fatalf("strong Lua-safe token was changed: %q -> %q", strong, got)
	}
}

// Documents WHY the F55 guard exists: emitting an unvalidated ZWSP token yields
// the Go %q ​ escape (invalid LuaJIT). The guard ensures the validators
// never RETURN such a token, so what reaches WriteLuaToken always compiles.
func TestLuaEmissionOfUnsafeTokenProducesInvalidEscape(t *testing.T) {
	t.Parallel()
	dir := filepath.Join(t.TempDir(), "lua")
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatalf("mkdir: %v", err)
	}
	p := filepath.Join(dir, "cfm_token.lua")
	tok := "tok" + zwsp + "end"
	if err := WriteLuaToken(p, tok, 0); err != nil {
		t.Fatalf("WriteLuaToken: %v", err)
	}
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	// The file must contain exactly the Go %q rendering (the \uXXXX form), and
	// NOT a literal ZWSP byte — proving the escape LuaJIT would reject.
	want := fmt.Sprintf("return %q", tok)
	if !strings.Contains(string(data), want) {
		t.Fatalf("emitted file missing %q, got: %q", want, string(data))
	}
	if strings.Contains(string(data), zwsp) {
		t.Fatalf("literal ZWSP should have been %%q-escaped, got: %q", string(data))
	}
}

// F54: a successful write leaves no .tmp sibling (the fsync rewrite must still
// rename cleanly and not orphan the temp file).
func TestWriteLuaTokenLeavesNoTmp(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	p := filepath.Join(dir, "cfm_token.lua")
	if err := WriteLuaToken(p, "abc123def456", 0); err != nil {
		t.Fatalf("WriteLuaToken: %v", err)
	}
	if _, err := os.Stat(p + ".tmp"); !os.IsNotExist(err) {
		t.Fatalf("expected no lingering .tmp, stat err=%v", err)
	}
	data, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("read: %v", err)
	}
	if !strings.Contains(string(data), `return "abc123def456"`) {
		t.Fatalf("unexpected content: %q", string(data))
	}
}
