package sslcollector

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"cfm/internal/logging"
)

// badTokens matches well-known placeholder values that must not be used in
// production. The check is case-insensitive and requires a full-string match.
var badTokens = regexp.MustCompile(`(?i)^(supersecret|changeme|secret|password|default|token|test|demo|placeholder)$`)

// confTokenLine patches the SSLCOLLECTOR_SOCK_TOKEN line in a cfm.conf file.
var confTokenLine = regexp.MustCompile(`(?m)^(SSLCOLLECTOR_SOCK_TOKEN\s*=\s*).*$`)

// ValidateOrGenerateToken returns current unchanged if it is strong (≥32 chars,
// not a known placeholder). Otherwise it generates a new 48-hex-char token,
// patches the SSLCOLLECTOR_SOCK_TOKEN line in cfgPath in place, and returns the
// new token.
//
// cfgPath may be empty; in that case the file-patch step is skipped (non-fatal)
// and the new token is still returned so the caller can update in-memory config.
func ValidateOrGenerateToken(cfgPath, current string) (string, error) {
	cur := strings.TrimSpace(current)
	if len(cur) >= 32 && !badTokens.MatchString(cur) {
		return cur, nil
	}

	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("sslcollector: token generation failed: %w", err)
	}
	token := hex.EncodeToString(b) // 48 hex chars

	if cfgPath != "" {
		// cfgPath is set at daemon startup from filepath.Join(cfgDir, "cfm.conf")
		// where cfgDir comes from a CLI flag or well-known path — never from
		// network input. Require an absolute path as a sanity guard.
		// #nosec G304 -- path is daemon-internal, not derived from user input
		if !filepath.IsAbs(cfgPath) {
			return token, fmt.Errorf("sslcollector: cfgPath must be absolute, got %q", cfgPath)
		}
		if data, err := os.ReadFile(cfgPath); err == nil { // #nosec G304
			updated := confTokenLine.ReplaceAllString(string(data), "${1}"+token)
			// Preserve the file's existing permissions (best-effort).
			info, statErr := os.Stat(cfgPath)
			mode := os.FileMode(0640)
			if statErr == nil {
				mode = info.Mode()
			}
			// #nosec G304 -- cfgPath is an absolute, daemon-internal config path
			_ = os.WriteFile(cfgPath, []byte(updated), mode)
		}
	}

	return token, nil
}

// ValidateOrGenerateTokenKey is the generic form of ValidateOrGenerateToken.
// Instead of patching the fixed SSLCOLLECTOR_SOCK_TOKEN key it patches keyName
// in cfgPath.  The function appends "keyName = <token>" if the key is not already
// present, so it works for keys that are absent on first install.
//
// cfgPath may be empty; in that case the file-patch step is skipped (non-fatal)
// and the new token is still returned so the caller can update in-memory config.
func ValidateOrGenerateTokenKey(cfgPath, keyName, current string) (string, error) {
	cur := strings.TrimSpace(current)
	if len(cur) >= 32 && !badTokens.MatchString(cur) {
		return cur, nil
	}

	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("sslcollector: token generation failed: %w", err)
	}
	token := hex.EncodeToString(b) // 48 hex chars

	if cfgPath != "" {
		// Require an absolute path as a sanity guard.
		if !filepath.IsAbs(cfgPath) {
			return token, fmt.Errorf("sslcollector: cfgPath must be absolute, got %q", cfgPath)
		}
		// Build a per-key regexp. keyName only contains [A-Z0-9_] so QuoteMeta is a no-op,
		// but we use it anyway for correctness.
		re := regexp.MustCompile(`(?mi)^(` + regexp.QuoteMeta(keyName) + `\s*=\s*).*$`)
		// #nosec G304 -- cfgPath is daemon-internal, not derived from user input
		if data, err := os.ReadFile(cfgPath); err == nil { // #nosec G304
			info, statErr := os.Stat(cfgPath)
			mode := os.FileMode(0640)
			if statErr == nil {
				mode = info.Mode()
			}
			var updated string
			if re.Match(data) {
				// Replace the existing key's value.
				updated = re.ReplaceAllString(string(data), "${1}"+token)
			} else {
				// Key absent: append it so it persists across restarts.
				s := string(data)
				if len(s) > 0 && s[len(s)-1] != '\n' {
					s += "\n"
				}
				updated = s + keyName + " = " + token + "\n"
			}
			// #nosec G304 -- cfgPath is an absolute, daemon-internal config path
			_ = os.WriteFile(cfgPath, []byte(updated), mode) // #nosec G306 -- preserve existing permissions
		}
	}

	return token, nil
}

// WriteLuaToken atomically writes a Lua module that returns the token string to
// luaPath. The file is created with mode 0640 (root:cfm) so that OpenResty
// workers running as the cfm group can read it, but world cannot.
// If cfmGID > 0 the file is chowned to root:cfmGID after the write.
//
// The generated file looks like:
//
//	-- AUTO-GENERATED by CFM — do not edit
//	return "deadbeef..."
func WriteLuaToken(luaPath, token string, cfmGID int) error {
	return writeLuaToken(luaPath, token, cfmGID, false)
}

// WriteLuaTokenWithMkdir is like WriteLuaToken, but it will create the parent
// directory (0750) when it does not already exist.
func WriteLuaTokenWithMkdir(luaPath, token string, cfmGID int) error {
	return writeLuaToken(luaPath, token, cfmGID, true)
}

// LuaTokenWriteResult describes the outcome of attempting to write a token file
// at a candidate path.
type LuaTokenWriteResult struct {
	Path    string
	Written bool
	Skipped bool
	Err     error
}

// WriteLuaTokenToExistingParents writes a Lua token module to each candidate
// path whose parent directory already exists. Missing parent directories are
// skipped so mixed OpenResty/Angie migrations can refresh whichever layout is
// present on disk without creating extra trees.
func WriteLuaTokenToExistingParents(token string, cfmGID int, candidates ...string) []LuaTokenWriteResult {
	seen := make(map[string]struct{}, len(candidates))
	results := make([]LuaTokenWriteResult, 0, len(candidates))
	for _, p := range candidates {
		p = strings.TrimSpace(p)
		if p == "" {
			continue
		}
		if _, ok := seen[p]; ok {
			continue
		}
		seen[p] = struct{}{}

		res := LuaTokenWriteResult{Path: p}
		dir := filepath.Dir(p)
		st, err := os.Stat(dir)
		if err != nil {
			if os.IsNotExist(err) {
				res.Skipped = true
				results = append(results, res)
				continue
			}
			res.Err = fmt.Errorf("sslcollector: stat parent directory %q for lua token target %q: %w", dir, p, err)
			results = append(results, res)
			continue
		}
		if !st.IsDir() {
			res.Err = fmt.Errorf("sslcollector: parent path %q for lua token target %q is not a directory", dir, p)
			results = append(results, res)
			continue
		}
		if err := writeLuaToken(p, token, cfmGID, false); err != nil {
			res.Err = err
			results = append(results, res)
			continue
		}
		res.Written = true
		results = append(results, res)
	}
	return results
}

func writeLuaToken(luaPath, token string, cfmGID int, mkdirParent bool) error {
	if !filepath.IsAbs(luaPath) {
		return fmt.Errorf("sslcollector: luaPath must be absolute, got %q", luaPath)
	}
	dir := filepath.Dir(luaPath)
	st, err := os.Stat(dir)
	if err != nil {
		if os.IsNotExist(err) {
			if !mkdirParent {
				return fmt.Errorf("sslcollector: missing parent directory %q for lua token target %q: %w", dir, luaPath, err)
			}
			if mkErr := os.MkdirAll(dir, 0750); mkErr != nil {
				return fmt.Errorf("sslcollector: create parent directory %q for lua token target %q: %w", dir, luaPath, mkErr)
			}
		} else {
			return fmt.Errorf("sslcollector: stat parent directory %q for lua token target %q: %w", dir, luaPath, err)
		}
	} else if !st.IsDir() {
		return fmt.Errorf("sslcollector: parent path %q for lua token target %q is not a directory", dir, luaPath)
	}

	content := fmt.Sprintf(
		"-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit\nreturn %q\n",
		token,
	)
	tmp := luaPath + ".tmp"
	// 0640: root owns, cfm group reads (required for OpenResty workers).
	// World has no access. gosec G306 flags anything above 0600 but group-read
	// is intentional here — 0600 would prevent OpenResty from reading the token.
	if err := os.WriteFile(tmp, []byte(content), 0640); err != nil { // #nosec G306
		return fmt.Errorf("sslcollector: write lua token tmp: %w", err)
	}
	if err := os.Chmod(tmp, 0640); err != nil {
		logging.Logf("[sslcollector] WARNING: failed chmod on tmp lua token %s: %v", tmp, err)
	}
	if cfmGID > 0 {
		if err := os.Chown(tmp, 0, cfmGID); err != nil {
			logging.Logf("[sslcollector] WARNING: failed chown on tmp lua token %s to root:%d: %v", tmp, cfmGID, err)
		}
	}
	if err := os.Rename(tmp, luaPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("sslcollector: rename lua token: %w", err)
	}
	if err := os.Chmod(luaPath, 0640); err != nil {
		logging.Logf("[sslcollector] WARNING: failed chmod on final lua token %s: %v", luaPath, err)
	}
	if cfmGID > 0 {
		if err := os.Chown(luaPath, 0, cfmGID); err != nil {
			logging.Logf("[sslcollector] WARNING: failed chown on final lua token %s to root:%d: %v", luaPath, cfmGID, err)
		}
	}
	return nil
}

// WriteLuaConfig atomically writes a Lua module with sslcollector runtime flags
// to luaPath (typically /var/lib/cfm/lua/cfm_sslcollector_config.lua).
// The file is created 0640 (root:cfm) so OpenResty workers can read it.
// sslcollector.lua loads this file at init_worker time to apply per-daemon config.
func WriteLuaConfig(luaPath string, offlineCache bool, cfmGID int) error {
	if !filepath.IsAbs(luaPath) {
		return fmt.Errorf("sslcollector: luaPath must be absolute, got %q", luaPath)
	}
	offlineCacheStr := "true"
	if !offlineCache {
		offlineCacheStr = "false"
	}
	content := fmt.Sprintf(
		"-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit\nreturn {\n  offline_cache = %s,\n}\n",
		offlineCacheStr,
	)
	tmp := luaPath + ".tmp"
	if err := os.WriteFile(tmp, []byte(content), 0640); err != nil { // #nosec G306 -- group-read intentional: cfm group = nginx workers only
		return fmt.Errorf("sslcollector: write lua config tmp: %w", err)
	}
	if err := os.Chmod(tmp, 0640); err != nil {
		logging.Logf("[sslcollector] WARNING: failed chmod on tmp lua config %s: %v", tmp, err)
	}
	if cfmGID > 0 {
		if err := os.Chown(tmp, 0, cfmGID); err != nil {
			logging.Logf("[sslcollector] WARNING: failed chown on tmp lua config %s to root:%d: %v", tmp, cfmGID, err)
		}
	}
	if err := os.Rename(tmp, luaPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("sslcollector: rename lua config: %w", err)
	}
	if cfmGID > 0 {
		_ = os.Chown(luaPath, 0, cfmGID)
	}
	return nil
}
