-- Standalone test for cfm_bridge_cfg (canonical accessor for the daemon-
-- published webdetector → edge-Lua knobs). Run with:
--   luajit scripts/tests/cfm_bridge_cfg_test.lua
--
-- Exercises the transform against the exact file shape written by Go's
-- sslcollector.WriteWebdetectorBridgeConfig, plus the missing-file
-- fallback and back-compat with an old daemon's file (clearance_refresh
-- only, no origin_* fields).

package.path = package.path .. ";configs/lua/?.lua;./?.lua"

local fake_now = 1000
_G.ngx = {
  now = function() return fake_now end,
  log = function(_, ...) end,
  WARN = 1, ERR = 2, INFO = 3, NOTICE = 4,
}

local fc = require "cfm_filecache"
local bc = require "cfm_bridge_cfg"

-- The module hardcodes the canonical path; point its cache entry at test
-- content by pre-seeding cfm_filecache is not possible (fc loads from
-- disk), so exercise the same transform through a patched loadfile that
-- serves our fixtures for the canonical path.
local PATH = "/var/lib/cfm/lua/cfm_bridge_config.lua"
local fixture = nil -- nil = file missing
local real_loadfile = loadfile
_G.loadfile = function(path)
  if path == PATH then
    if fixture == nil then return nil, "no such file" end
    return assert((loadstring or load)(fixture))
  end
  return real_loadfile(path)
end

local failures = 0
local function check(cond, msg)
  if cond then
    print("ok   - " .. msg)
  else
    failures = failures + 1
    print("FAIL - " .. msg)
  end
end

local function expire()
  fake_now = fake_now + 60 -- step past the 10s TTL
  fc.entries[PATH] = nil   -- and drop any cached failure entry
end

-- 1) Missing file → fail-safe fallback shape.
local cfg = bc.get()
check(cfg.clearance_refresh == true, "missing file: clearance_refresh defaults true")
check(cfg.origin_keepalive == nil, "missing file: origin_keepalive stays nil (env fallback applies)")

-- 2) Exact shape written by sslcollector.WriteWebdetectorBridgeConfig.
expire()
fixture = table.concat({
  "-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit",
  "return {",
  "  clearance_refresh = true,",
  "  origin_keepalive = true,",
  "  origin_ka_idle_sec = 3,",
  "  origin_ka_max_reqs = 1000,",
  "}",
}, "\n")
cfg = bc.get()
check(cfg.clearance_refresh == true, "daemon file: clearance_refresh parsed")
check(cfg.origin_keepalive == true, "daemon file: origin_keepalive=true parsed")
check(cfg.origin_ka_idle_sec == 3, "daemon file: idle_sec parsed as number")
check(cfg.origin_ka_max_reqs == 1000, "daemon file: max_reqs parsed as number")

-- 3) Knob off is an explicit false, NOT nil — the config key must beat any
--    env fallback (config-file-wins precedence in cfm.lua depends on this).
expire()
fixture = "return { clearance_refresh = true, origin_keepalive = false, origin_ka_idle_sec = 3, origin_ka_max_reqs = 1000 }"
cfg = bc.get()
check(cfg.origin_keepalive == false, "explicit off: origin_keepalive is false (not nil)")

-- 4) Old daemon's file (pre-origin-keepalive): fields absent → nil, so
--    cfm.lua falls back to the env var.
expire()
fixture = "return { clearance_refresh = false }"
cfg = bc.get()
check(cfg.clearance_refresh == false, "old daemon file: clearance_refresh=false honoured")
check(cfg.origin_keepalive == nil, "old daemon file: origin_keepalive nil → env fallback")
check(cfg.origin_ka_idle_sec == nil, "old daemon file: idle_sec nil → env fallback")

-- 5) Garbage file → fallback, not a crash.
expire()
fixture = "return 42"
cfg = bc.get()
check(cfg.clearance_refresh == true and cfg.origin_keepalive == nil,
      "non-table file: fail-safe fallback served")

-- ── token() accessor ─────────────────────────────────────────────────────────
-- Same loadfile-patch trick for the token path; every edge consumer
-- (cfm.lua, cfm_panel, cfm_purge, cfm_h3_config) goes through this single
-- load+validate implementation.
local TOKEN_PATH = "/var/lib/cfm/lua/cfm_bridge_token.lua"
local token_fixture = nil
local prev_loadfile = _G.loadfile
_G.loadfile = function(path)
  if path == TOKEN_PATH then
    if token_fixture == nil then return nil, "no such file" end
    return assert((loadstring or load)(token_fixture))
  end
  return prev_loadfile(path)
end
local function expire_token()
  fake_now = fake_now + 60
  fc.entries[TOKEN_PATH] = nil
end

-- 6) Missing token file → (nil, err); daemon not started yet.
local tok, terr = bc.token()
check(tok == nil and terr ~= nil, "missing token file: nil + err")

-- 7) Valid token (exact shape written by sslcollector.WriteLuaToken).
expire_token()
token_fixture = '-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit\nreturn "0123456789abcdef0123456789abcdef0123456789abcdef"'
tok = bc.token()
check(tok == "0123456789abcdef0123456789abcdef0123456789abcdef",
      "daemon-written token file parses")

-- 8) Cached within TTL: rotation on disk is not seen until expiry (10s max).
token_fixture = 'return "ffffffffffffffffffffffffffffffffffffffffffffffff"'
fake_now = fake_now + 5
check(bc.token() == "0123456789abcdef0123456789abcdef0123456789abcdef",
      "token served from cache within TTL")
expire_token()
check(bc.token() == "ffffffffffffffffffffffffffffffffffffffffffffffff",
      "rotated token picked up after TTL expiry")

-- 8b) refresh_token() bypasses the TTL: an inbound-credential validator
-- (cfm_purge) must be able to see a just-rotated token immediately.
token_fixture = 'return "1111111111111111111111111111111111111111111111ff"'
fake_now = fake_now + 1 -- still inside the fresh TTL window
check(bc.token() == "ffffffffffffffffffffffffffffffffffffffffffffffff",
      "cached token still served inside TTL before refresh")
check(bc.refresh_token() == "1111111111111111111111111111111111111111111111ff",
      "refresh_token() re-reads the file immediately, ignoring the TTL")
check(bc.token() == "1111111111111111111111111111111111111111111111ff",
      "refresh_token() repopulates the cache for subsequent token() calls")

-- 9) Too-short / non-string tokens are rejected, not served.
expire_token()
token_fixture = 'return "short"'
tok, terr = bc.token()
check(tok == nil and tostring(terr):find("invalid or too short", 1, true) ~= nil,
      "short token rejected with descriptive err")
expire_token()
token_fixture = 'return { not_a_string = true }'
tok = bc.token()
check(tok == nil, "non-string token rejected")

if failures > 0 then
  print(string.format("%d failure(s)", failures))
  os.exit(1)
end
print("OK: cfm_bridge_cfg parses daemon-written knobs, old-daemon files and failure shapes correctly")
