-- Standalone test for cfm_bridge_cfg (canonical accessor for the daemon-
-- published webdetector → edge-Lua knobs). Run with:
--   luajit scripts/tests/cfm_bridge_cfg_test.lua
--
-- Exercises the transform against the exact file shape written by Go's
-- sslcollector.WriteWebdetectorBridgeConfig, plus the missing-file
-- fallback and back-compat with an old daemon's file (clearance_refresh
-- only, no origin_* fields).

package.path = package.path .. ";configs/lua/?.lua;./?.lua"

local fake_now = 1000
_G.ngx = {
  now = function() return fake_now end,
  log = function(_, ...) end,
  WARN = 1, ERR = 2, INFO = 3, NOTICE = 4,
}

local fc = require "cfm_filecache"
local bc = require "cfm_bridge_cfg"

-- The module hardcodes the canonical path; point its cache entry at test
-- content by pre-seeding cfm_filecache is not possible (fc loads from
-- disk), so exercise the same transform through a patched loadfile that
-- serves our fixtures for the canonical path.
local PATH = "/var/lib/cfm/lua/cfm_bridge_config.lua"
local fixture = nil -- nil = file missing
local real_loadfile = loadfile
_G.loadfile = function(path)
  if path == PATH then
    if fixture == nil then return nil, "no such file" end
    return assert((loadstring or load)(fixture))
  end
  return real_loadfile(path)
end

local failures = 0
local function check(cond, msg)
  if cond then
    print("ok   - " .. msg)
  else
    failures = failures + 1
    print("FAIL - " .. msg)
  end
end

local function expire()
  fake_now = fake_now + 60 -- step past the 10s TTL
  fc.entries[PATH] = nil   -- and drop any cached failure entry
end

-- 1) Missing file → fail-safe fallback shape.
local cfg = bc.get()
check(cfg.clearance_refresh == true, "missing file: clearance_refresh defaults true")
check(cfg.origin_keepalive == nil, "missing file: origin_keepalive stays nil (env fallback applies)")

-- 2) Exact shape written by sslcollector.WriteWebdetectorBridgeConfig.
expire()
fixture = table.concat({
  "-- AUTO-GENERATED by CFM \xe2\x80\x94 do not edit",
  "return {",
  "  clearance_refresh = true,",
  "  origin_keepalive = true,",
  "  origin_ka_idle_sec = 3,",
  "  origin_ka_max_reqs = 1000,",
  "}",
}, "\n")
cfg = bc.get()
check(cfg.clearance_refresh == true, "daemon file: clearance_refresh parsed")
check(cfg.origin_keepalive == true, "daemon file: origin_keepalive=true parsed")
check(cfg.origin_ka_idle_sec == 3, "daemon file: idle_sec parsed as number")
check(cfg.origin_ka_max_reqs == 1000, "daemon file: max_reqs parsed as number")

-- 3) Knob off is an explicit false, NOT nil — the config key must beat any
--    env fallback (config-file-wins precedence in cfm.lua depends on this).
expire()
fixture = "return { clearance_refresh = true, origin_keepalive = false, origin_ka_idle_sec = 3, origin_ka_max_reqs = 1000 }"
cfg = bc.get()
check(cfg.origin_keepalive == false, "explicit off: origin_keepalive is false (not nil)")

-- 4) Old daemon's file (pre-origin-keepalive): fields absent → nil, so
--    cfm.lua falls back to the env var.
expire()
fixture = "return { clearance_refresh = false }"
cfg = bc.get()
check(cfg.clearance_refresh == false, "old daemon file: clearance_refresh=false honoured")
check(cfg.origin_keepalive == nil, "old daemon file: origin_keepalive nil → env fallback")
check(cfg.origin_ka_idle_sec == nil, "old daemon file: idle_sec nil → env fallback")

-- 5) Garbage file → fallback, not a crash.
expire()
fixture = "return 42"
cfg = bc.get()
check(cfg.clearance_refresh == true and cfg.origin_keepalive == nil,
      "non-table file: fail-safe fallback served")

if failures > 0 then
  print(string.format("%d failure(s)", failures))
  os.exit(1)
end
print("OK: cfm_bridge_cfg parses daemon-written knobs, old-daemon files and failure shapes correctly")
