-- Go↔Lua parity for the Site Cache edge feed. The fixture is generated by
-- internal/webdetector/site_cache_edge_parity_test.go: the /nginx/cache/config
-- body exactly as the daemon serves it, and the daemon's StatsKeyFor (its
-- mirror of policy_key_for) for a set of request hosts. This feeds the same
-- body to the real cfm_cache.lua and asserts the edge
--   * counts every request host under the key the daemon expects (the daemon
--     keeps and serves stats rows by that key),
--   * pushes the stats of exactly the feed's armed keys (the real
--     maybe_flush_stats → stats_flush_handler path, with cfm_cache_log
--     stubbed to record what it is asked to read), and
--   * knows every field of the feed and keeps each one in the policy it
--     applies (a field the daemon adds that the edge does not know fails
--     here, so it is a decision, not a silent no-op).

package.path = "configs/lua/?.lua;" .. package.path

local _pushed      -- what the stats push encodes
local BODY = "<encoded-stats-body>"
package.loaded["cjson.safe"] = { decode = function() return nil end,
                                 encode = function(t) _pushed = t; return BODY end }
package.loaded["cfm_bridge_cfg"] = {
  get   = function() return { site_cache = true, micro_cache_enforce = false } end,
  token = function() return "tok" end,
}
-- the bridge socket: records every request, answers 200
local _sent = {}
local function fake_socket()
  return {
    settimeouts = function() end,
    connect     = function(_, addr) _sent.addr = addr; return true end,
    send        = function(_, req) _sent[#_sent + 1] = req; return #req end,
    receive     = function() return "HTTP/1.1 200 OK" end,
    close       = function() return true end,
  }
end
package.loaded["cfm_selfip"] = { is_self_origin = function() return false end }

local _now, _timers = 0, {}          -- 0 keeps the async refresh a no-op
_G.ngx = {
  config = { nginx_version = 1025003 },
  req    = { is_internal = function() return false end },
  now    = function() return _now end,
  timer  = { at = function(_, fn) _timers[#_timers + 1] = fn; return true end },
  log    = function() end,
  md5    = function(s) return s end,
  shared = { cfm_decisions = { add = function() return true end } },
  WARN = 1, ERR = 2,
  socket = { tcp = fake_socket },
  var    = { host = "" },
  header = {},
}

local cache = require("cfm_cache")
local fx = dofile("scripts/tests/fixtures/site_cache_edge_parity.lua")

local fails = 0
local function check(c, m)
  if c then return end
  fails = fails + 1
  io.stderr:write("FAIL: " .. m .. "\n")
end

local entries = fx.feed.entries
check(type(entries) == "table" and #entries > 0, "fixture feed has entries")

-- Every field of the feed is one cfm_cache.lua knows (rebuild_cache keeps
-- the tiers as tables; on/ttl decide, recipe labels the debug header).
local KNOWN = { host = true, gen = true, static = true, micro = true, strict_cookies = true, auth_cookies = true }
local KNOWN_TIER = { on = true, recipe = true, ttl = true }
for _, e in ipairs(entries) do
  for k, v in pairs(e) do
    check(KNOWN[k], "feed field '" .. tostring(k) .. "' (" .. tostring(e.host) .. ") is not one cfm_cache.lua knows — teach it (and this list) or leave it out of the feed")
    if k == "static" or k == "micro" then
      for tk in pairs(v) do
        check(KNOWN_TIER[tk], "feed tier field '" .. k .. "." .. tostring(tk) .. "' is not one cfm_cache.lua knows")
      end
    end
  end
end

-- a deep copy: the edge must keep each field, not merely the daemon's table
local function copy(v)
  if type(v) ~= "table" then return v end
  local o = {}
  for k, x in pairs(v) do o[k] = copy(x) end
  return o
end
cache._rebuild_cache(copy(entries))

-- 1) the stats key of every request host is the daemon's
for _, c in ipairs(fx.cases) do
  local want = c.key or nil
  local got = cache.policy_key_for(c.host)
  check(got == want, string.format("policy_key_for(%q) = %s, daemon StatsKeyFor = %s",
    c.host, tostring(got), tostring(want)))
end

-- 2) the stats push reads, and pushes, exactly the feed's armed keys — through
--    the real flush path (the log phase calls maybe_flush_stats)
local asked, served = nil, {}
package.loaded["cfm_cache_log"] = { snapshot_vhosts = function(keys)
  asked = keys
  local out = {}
  for i, k in ipairs(keys or {}) do out[k] = { HIT = i, MISS = 100 + i }; served[k] = out[k] end
  return out
end }
_now = 1000
cache.maybe_flush_stats()
check(#_timers == 1, "maybe_flush_stats scheduled " .. #_timers .. " timer(s), want 1 (the stats flush)")
if _timers[1] then _timers[1](false) end
local function sorted(list)
  local o = {}
  for _, k in ipairs(list or {}) do o[#o + 1] = k end
  table.sort(o)
  return table.concat(o, ",")
end
local want_keys = table.concat(fx.armed_keys, ",")
check(sorted(asked) == want_keys, "the flush asked snapshot_vhosts for [" .. sorted(asked) .. "], daemon armed keys [" .. want_keys .. "]")
local pushed_hosts = {}
for _, r in ipairs((_pushed and _pushed.rows) or {}) do
  pushed_hosts[#pushed_hosts + 1] = r.host
  local want = served[r.host]
  check(want and type(r.counts) == "table" and r.counts.HIT == want.HIT and r.counts.MISS == want.MISS,
        "row " .. tostring(r.host) .. " does not carry the counts snapshot_vhosts read for it")
end
check(sorted(pushed_hosts) == want_keys, "the push carries rows [" .. sorted(pushed_hosts) .. "], daemon armed keys [" .. want_keys .. "]")
-- ...and it reached the bridge: one POST to /nginx/cache/stats, token and
-- exact length, with the encoded body
check(#_sent == 1, #_sent .. " bridge request(s) sent, want 1")
local req = _sent[1] or ""
check(_sent.addr == "unix:/var/run/cfm/cfm_nginx.sock", "the push connects to " .. tostring(_sent.addr))
check(req:sub(1, #"POST /nginx/cache/stats HTTP/1.1\r\n") == "POST /nginx/cache/stats HTTP/1.1\r\n", "the push is not POST /nginx/cache/stats: " .. req:sub(1, 60))
check(req:find("\r\nX%-CFM%-Token: tok\r\n") ~= nil, "the push carries no bridge token")
check(req:sub(-#("Content-Length: " .. #BODY .. "\r\n\r\n" .. BODY)) == "Content-Length: " .. #BODY .. "\r\n\r\n" .. BODY,
      "the push body is not the encoded rows with its exact Content-Length")

-- 3) each row's fields land in the policy the edge applies to its host
local function same_list(a, b)
  a, b = a or {}, b or {}
  if #a ~= #b then return false end
  for i = 1, #a do if a[i] ~= b[i] then return false end end
  return true
end
local function same_tier(p, e)
  if e == nil then return p == nil or not p.on end
  return type(p) == "table" and p.on == e.on and p.ttl == e.ttl and p.recipe == e.recipe
end
for _, e in ipairs(entries) do
  -- a wildcard is probed with a sub-host only it matches (no narrower
  -- pattern in the fixture starts with "zz-probe.")
  local probe = e.host
  if probe:sub(1, 2) == "*." then probe = "zz-probe." .. probe:sub(3) end
  local p = cache.policy_for(probe)
  check(p ~= nil, "no policy for " .. probe .. " (row " .. e.host .. ")")
  if p then
    check(p.gen == e.gen, e.host .. ": gen " .. tostring(p.gen) .. " vs feed " .. tostring(e.gen))
    check(same_tier(p.static, e.static), e.host .. ": static tier not as fed")
    check(same_tier(p.micro, e.micro), e.host .. ": micro tier not as fed")
    check(p.strict_cookies == (e.strict_cookies == true), e.host .. ": strict_cookies not as fed")
    check(same_list(p.auth_cookies, e.auth_cookies), e.host .. ": auth_cookies not as fed")
  end
end

if fails > 0 then io.stderr:write(fails .. " failure(s)\n"); os.exit(1) end
print("OK cfm_cache_edge_parity_test (" .. #fx.cases .. " hosts, " .. #entries .. " feed rows)")
