-- Go↔Lua parity for the Site Cache edge feed. The fixture is generated by
-- internal/webdetector/site_cache_edge_parity_test.go: the /nginx/cache/config
-- body exactly as the daemon serves it, and the daemon's StatsKeyFor (its
-- mirror of policy_key_for) for a set of request hosts. This feeds the same
-- body to the real cfm_cache.lua and asserts the edge
--   * counts every request host under the key the daemon expects (the daemon
--     keeps and serves stats rows by that key),
--   * reads the stats of exactly the feed's armed keys, and
--   * understands every field of the feed (a field the daemon adds that the
--     edge does not read fails here, so it is a decision, not a silent no-op).

package.path = "configs/lua/?.lua;" .. package.path

package.loaded["cjson.safe"] = { decode = function() return nil end }
package.loaded["cfm_bridge_cfg"] = { get = function()
  return { site_cache = true, micro_cache_enforce = false }
end }
package.loaded["cfm_selfip"] = { is_self_origin = function() return false end }

_G.ngx = {
  config = { nginx_version = 1025003 },
  req    = { is_internal = function() return false end },
  now    = function() return 0 end,    -- 0 keeps the async refresh a no-op
  timer  = { at = function() return true end },
  log    = function() end,
  md5    = function(s) return s end,
  shared = {},
  WARN = 1, ERR = 2,
  var    = { host = "" },
  header = {},
}

local cache = require("cfm_cache")
local fx = dofile("scripts/tests/fixtures/site_cache_edge_parity.lua")

local fails = 0
local function check(c, m)
  if c then return end
  fails = fails + 1
  io.stderr:write("FAIL: " .. m .. "\n")
end

local entries = fx.feed.entries
check(type(entries) == "table" and #entries > 0, "fixture feed has entries")

-- Every field of the feed is one cfm_cache.lua rebuild_cache reads.
local KNOWN = { host = true, gen = true, static = true, micro = true, strict_cookies = true, auth_cookies = true }
local KNOWN_TIER = { on = true, recipe = true, ttl = true }
for _, e in ipairs(entries) do
  for k, v in pairs(e) do
    check(KNOWN[k], "feed field '" .. tostring(k) .. "' (" .. tostring(e.host) .. ") is not read by cfm_cache.lua")
    if k == "static" or k == "micro" then
      for tk in pairs(v) do
        check(KNOWN_TIER[tk], "feed tier field '" .. k .. "." .. tostring(tk) .. "' is not read by cfm_cache.lua")
      end
    end
  end
end

cache._rebuild_cache(entries)

-- 1) the stats key of every request host is the daemon's
for _, c in ipairs(fx.cases) do
  local want = c.key or nil
  local got = cache.policy_key_for(c.host)
  check(got == want, string.format("policy_key_for(%q) = %s, daemon StatsKeyFor = %s",
    c.host, tostring(got), tostring(want)))
end

-- 2) the stats push reads exactly the feed's armed keys
local got_keys = {}
for _, k in ipairs(cache._stats_keys()) do got_keys[#got_keys + 1] = k end
table.sort(got_keys)
check(table.concat(got_keys, ",") == table.concat(fx.armed_keys, ","),
  "stats_keys = " .. table.concat(got_keys, ",") .. ", daemon armed keys = " .. table.concat(fx.armed_keys, ","))

-- 3) each row's fields land in the policy the edge applies to its host
local function same_list(a, b)
  a, b = a or {}, b or {}
  if #a ~= #b then return false end
  for i = 1, #a do if a[i] ~= b[i] then return false end end
  return true
end
local function same_tier(p, e)
  if e == nil then return p == nil or not p.on end
  return type(p) == "table" and p.on == e.on and p.ttl == e.ttl and p.recipe == e.recipe
end
for _, e in ipairs(entries) do
  -- a wildcard is probed with a sub-host only it matches (no narrower
  -- pattern in the fixture starts with "zz-probe.")
  local probe = e.host
  if probe:sub(1, 2) == "*." then probe = "zz-probe." .. probe:sub(3) end
  local p = cache.policy_for(probe)
  check(p ~= nil, "no policy for " .. probe .. " (row " .. e.host .. ")")
  if p then
    check(p.gen == e.gen, e.host .. ": gen " .. tostring(p.gen) .. " vs feed " .. tostring(e.gen))
    check(same_tier(p.static, e.static), e.host .. ": static tier not as fed")
    check(same_tier(p.micro, e.micro), e.host .. ": micro tier not as fed")
    check(p.strict_cookies == (e.strict_cookies == true), e.host .. ": strict_cookies not as fed")
    check(same_list(p.auth_cookies, e.auth_cookies), e.host .. ": auth_cookies not as fed")
  end
end

if fails > 0 then io.stderr:write(fails .. " failure(s)\n"); os.exit(1) end
print("OK cfm_cache_edge_parity_test (" .. #fx.cases .. " hosts, " .. #entries .. " feed rows)")
