package sysctl

import (
	"errors"
	"io"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"

	cfg "cfm/internal/config"
	"cfm/internal/managedsysctl"
)

func TestApplyTweaksMissingKeyLoggedAndDoesNotStopLaterKeys(t *testing.T) {
	const missingKey = "net.ipv6.conf.all.send_redirects"
	calls := []string{}
	managedsysctl.SetSetCommandForTest(t, func(key, value string) ([]byte, error) {
		calls = append(calls, key)
		if key == missingKey {
			return []byte("sysctl: cannot stat /proc/sys/net/ipv6/conf/all/send_redirects"), errors.New("exit status 1")
		}
		return []byte(key + " = " + value), nil
	})

	stderr := captureStderr(t, func() {
		err := ApplyTweaks(&cfg.SystemTweaksConfig{
			Enable:         true,
			Persist:        false,
			TCPLooseStrict: true,
			CTMin:          1024,
			CTMax:          2048,
			CTPerGB:        1,
		})
		if err != nil {
			t.Fatalf("ApplyTweaks returned error for best-effort runtime failure: %v", err)
		}
	})

	if !strings.Contains(stderr, "sysctl: 1 key(s) rejected by kernel") {
		t.Fatalf("stderr did not include aggregated ApplyResult error: %q", stderr)
	}
	if !strings.Contains(stderr, missingKey+"=0") || !strings.Contains(stderr, "cannot stat /proc/sys") {
		t.Fatalf("stderr did not identify the missing key and kernel response: %q", stderr)
	}

	missingIdx := indexOf(calls, missingKey)
	laterIdx := indexOf(calls, "net.ipv6.conf.default.accept_redirects")
	if missingIdx < 0 {
		t.Fatalf("missing key was not attempted; calls=%v", calls)
	}
	if laterIdx < 0 || laterIdx <= missingIdx {
		t.Fatalf("expected keys after the missing key to be attempted; missingIdx=%d laterIdx=%d calls=%v", missingIdx, laterIdx, calls)
	}
}

func TestPersistSysctlFileDeterministicAndAtomic(t *testing.T) {
	first := map[string]string{
		"net.ipv4.conf.default.send_redirects": "0",
		"net.ipv4.tcp_syncookies":              "1",
		"net.netfilter.nf_conntrack_max":       "262144",
		"net.ipv4.tcp_syn_retries":             "3",
		"net.future.zzz":                       "9",
		"net.future.aaa":                       "8",
	}
	second := map[string]string{
		"net.future.zzz":                       "9",
		"net.ipv4.tcp_syn_retries":             "3",
		"net.netfilter.nf_conntrack_max":       "262144",
		"net.future.aaa":                       "8",
		"net.ipv4.tcp_syncookies":              "1",
		"net.ipv4.conf.default.send_redirects": "0",
	}

	dir := t.TempDir()
	path := filepath.Join(dir, "99-cfm.conf")
	if err := persistSysctlFileTo(path, kvMapToManagedPairs(first)); err != nil {
		t.Fatalf("first persist failed: %v", err)
	}
	firstContent, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read first persist: %v", err)
	}
	if err := persistSysctlFileTo(path, kvMapToManagedPairs(second)); err != nil {
		t.Fatalf("second persist failed: %v", err)
	}
	secondContent, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read second persist: %v", err)
	}
	if string(firstContent) != string(secondContent) {
		t.Fatalf("persist output is not deterministic:\nfirst:\n%s\nsecond:\n%s", firstContent, secondContent)
	}

	want := "# Generated by CFM - DO NOT EDIT\n" +
		"# Apply at boot via systemd-sysctl.\n" +
		"net.ipv4.tcp_syncookies = 1\n" +
		"net.ipv4.tcp_syn_retries = 3\n" +
		"net.netfilter.nf_conntrack_max = 262144\n" +
		"net.ipv4.conf.default.send_redirects = 0\n" +
		"net.future.aaa = 8\n" +
		"net.future.zzz = 9\n"
	if got := string(firstContent); got != want {
		t.Fatalf("persist content mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}

	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatalf("read temp dir: %v", err)
	}
	for _, e := range entries {
		if strings.Contains(e.Name(), ".tmp-") {
			t.Fatalf("atomic write temp file was not cleaned up: %s", e.Name())
		}
	}
}

func TestManagedKeysOwnershipUnchanged(t *testing.T) {
	want := []string{
		"net.ipv4.tcp_syncookies",
		"net.ipv4.tcp_syn_retries",
		"net.ipv4.tcp_synack_retries",
		"net.ipv4.tcp_fin_timeout",
		"net.netfilter.nf_conntrack_max",
		"net.netfilter.nf_conntrack_tcp_timeout_time_wait",
		"net.netfilter.nf_conntrack_tcp_timeout_fin_wait",
		"net.netfilter.nf_conntrack_tcp_timeout_close_wait",
		"net.netfilter.nf_conntrack_tcp_loose",
		"net.ipv4.conf.all.rp_filter",
		"net.ipv4.conf.all.accept_redirects",
		"net.ipv4.conf.all.send_redirects",
		"net.ipv4.conf.default.rp_filter",
		"net.ipv4.conf.default.accept_redirects",
		"net.ipv4.conf.default.send_redirects",
		"net.ipv4.conf.all.route_localnet",
		"net.ipv4.conf.default.route_localnet",
		"net.ipv6.conf.all.accept_redirects",
		"net.ipv6.conf.all.send_redirects",
		"net.ipv6.conf.default.accept_redirects",
		"net.ipv6.conf.default.send_redirects",
	}
	got := ManagedKeys()
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("ManagedKeys changed:\ngot  %#v\nwant %#v", got, want)
	}

	r := managedsysctl.NewRegistry()
	r.Register(catalog{})
	for _, key := range want {
		if owner := r.OwnerOf(key); owner != managedsysctl.OwnerSysTweaks {
			t.Fatalf("OwnerOf(%q)=%q, want %q", key, owner, managedsysctl.OwnerSysTweaks)
		}
	}
	if conflicts := r.Conflicts(); len(conflicts) != 0 {
		t.Fatalf("sys_tweaks catalog should not conflict with itself, got %v", conflicts)
	}
}

func captureStderr(t *testing.T, fn func()) string {
	t.Helper()
	old := os.Stderr
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatalf("pipe stderr: %v", err)
	}
	os.Stderr = w
	defer func() { os.Stderr = old }()

	fn()

	if err := w.Close(); err != nil {
		t.Fatalf("close stderr writer: %v", err)
	}
	out, err := io.ReadAll(r)
	if err != nil {
		t.Fatalf("read stderr: %v", err)
	}
	if err := r.Close(); err != nil {
		t.Fatalf("close stderr reader: %v", err)
	}
	return string(out)
}

func indexOf(xs []string, want string) int {
	for i, x := range xs {
		if x == want {
			return i
		}
	}
	return -1
}
