package sysctl

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	cfg "cfm/internal/config"
)

const persistPath = "/etc/sysctl.d/99-cfm.conf"

func ApplyTweaks(c *cfg.SystemTweaksConfig) error {
	if c == nil || !c.Enable {
		return nil
	}
	// Defaults guard (σε περίπτωση που δεν έχεις καλέσει setDefaults νωρίτερα)
	c.SetDefaults()

	// 1) Conntrack sizing από RAM
	memGB, _ := readMemGB()
	targetCT := clamp(memGB*c.CTPerGB, c.CTMin, c.CTMax)

	// 2) Φτιάξε key→value pairs για runtime write
	kv := map[string]string{
		// Conntrack
		"net/netfilter/nf_conntrack_max":                          itoa(targetCT),
		// Strictness / timeouts
		"net/ipv4/tcp_syn_retries":                                itoa(c.TCPSynRetries),
		"net/ipv4/tcp_synack_retries":                             itoa(c.TCPSynAckRetries),
		"net/ipv4/tcp_fin_timeout":                                itoa(c.TCPFinTimeout),
		"net/netfilter/nf_conntrack_tcp_timeout_time_wait":        itoa(c.CTTimeWait),
		"net/netfilter/nf_conntrack_tcp_timeout_fin_wait":         itoa(c.CTFinWait),
		"net/netfilter/nf_conntrack_tcp_timeout_close_wait":       itoa(c.CTCloseWait),
		// Hygiene
		"net/ipv4/conf/all/rp_filter":                             itoa(c.RPFilter),
		"net/ipv4/conf/all/accept_redirects":                      bool01(c.AcceptRedirects),
		"net/ipv4/conf/all/send_redirects":                        bool01(c.SendRedirects),

    "net/ipv4/conf/default/rp_filter":                    itoa(c.RPFilter),
    "net/ipv4/conf/default/accept_redirects":             bool01(c.AcceptRedirects),
    "net/ipv4/conf/default/send_redirects":               bool01(c.SendRedirects),

    // IPv6 hygiene (safe defaults)
    "net/ipv6/conf/all/accept_redirects":                 "0",
    "net/ipv6/conf/all/send_redirects":                   "0",
    "net/ipv6/conf/default/accept_redirects":             "0",
    "net/ipv6/conf/default/send_redirects":               "0",

    // Needed for DNAT -> 127.0.0.1 (challenge loopback listeners)
    // Default ON (when SYS_TWEAKS_ENABLE=1)
    "net/ipv4/conf/all/route_localnet":                   "1",
    "net/ipv4/conf/default/route_localnet":               "1",

	// Safety net (συμπληρωματικό)
	"net/ipv4/tcp_syncookies":                                 "1",
	}

	// nf_conntrack_tcp_loose -> 0 όταν strict
	if c.TCPLooseStrict {
		kv["net/netfilter/nf_conntrack_tcp_loose"] = "0"
	}

	// 3) Apply live
	for k, v := range kv {
		if err := writeProcSys(k, v); err != nil {
			// δεν “σπάμε” το σύστημα — απλώς ενημερώνουμε
			// (μπορεί π.χ. κάποιο key να μην υπάρχει σε παλιότερο kernel)
			fmt.Fprintf(os.Stderr, "sysctl: apply %s=%s failed: %v\n", k, v, err)
		}
	}

	// 3a) Προσπάθησε να ρυθμίσεις hashsize (όπου επιτρέπεται)
	trySetHashsize(targetCT / 4) // best-effort

	// 4) Persist (αν ζητηθεί)
	if c.Persist {
		if err := persistSysctlFile(kv); err != nil {
			return fmt.Errorf("persist sysctl file: %w", err)
		}
	}
	return nil
}

func readMemGB() (int, error) {
	f, err := os.Open("/proc/meminfo")
	if err != nil {
		return 0, err
	}
	defer f.Close()

	var kb int64
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "MemTotal:") {
			fields := strings.Fields(line)
			if len(fields) >= 2 {
				// MemTotal σε kB
				kb, _ = strconv.ParseInt(fields[1], 10, 64)
				break
			}
		}
	}
	if kb <= 0 {
		return 0, errors.New("cannot read MemTotal")
	}
	gb := int((kb + (1024*1024 - 1)) / (1024 * 1024)) // round-up to GB
	if gb <= 0 {
		gb = 1
	}
	return gb, nil
}

func clamp(v, lo, hi int) int {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

func bool01(b bool) string {
	if b {
		return "1"
	}
	return "0"
}

func itoa(i int) string { return strconv.Itoa(i) }

func writeProcSys(key, val string) error {
	path := filepath.Join("/proc/sys", filepath.FromSlash(key))
	return os.WriteFile(path, []byte(strings.TrimSpace(val)), 0600)
}

func persistSysctlFile(kv map[string]string) error {
	var b strings.Builder
	b.WriteString("# Generated by CFM - DO NOT EDIT\n")
	b.WriteString("# Apply at boot via systemd-sysctl.\n")
	// Για σταθερότητα, γράψε τα κλειδιά με “γνωστή” σειρά
	keys := []string{
		"net.ipv4.tcp_syncookies",
		"net.ipv4.tcp_syn_retries",
		"net.ipv4.tcp_synack_retries",
		"net.ipv4.tcp_fin_timeout",
		"net.netfilter.nf_conntrack_max",
		"net.netfilter.nf_conntrack_tcp_timeout_time_wait",
		"net.netfilter.nf_conntrack_tcp_timeout_fin_wait",
		"net.netfilter.nf_conntrack_tcp_timeout_close_wait",
		"net.netfilter.nf_conntrack_tcp_loose",
		"net.ipv4.conf.all.rp_filter",
		"net.ipv4.conf.all.accept_redirects",
		"net.ipv4.conf.all.send_redirects",
    "net.ipv4.conf.default.rp_filter",
    "net.ipv4.conf.default.accept_redirects",
    "net.ipv4.conf.default.send_redirects",
    "net.ipv4.conf.all.route_localnet",
    "net.ipv4.conf.default.route_localnet",
    "net.ipv6.conf.all.accept_redirects",
    "net.ipv6.conf.all.send_redirects",
    "net.ipv6.conf.default.accept_redirects",
    "net.ipv6.conf.default.send_redirects",
	}
	// Γράψε μόνο όσα υπήρχαν στο kv
	for _, k := range keys {
 kProc := strings.ReplaceAll(k, ".", "/")
 if v, ok := kv[kProc]; ok {
			fmt.Fprintf(&b, "%s = %s\n", k, v)
		}
	}
	return os.WriteFile(persistPath, []byte(b.String()), 0600)
}

// Best-effort set hashsize (τρέχει μόνο αν υπάρχει parameter file)
func trySetHashsize(v int) {
	if v <= 0 {
		return
	}
	path := "/sys/module/nf_conntrack/parameters/hashsize"
	// Αν δεν υπάρχει, το kernel δεν επιτρέπει runtime write (χρειάζεται modprobe param).
	// Δεν θεωρείται σφάλμα.
	if _, err := os.Stat(path); err == nil {
		_ = os.WriteFile(path, []byte(itoa(v)), 0600)
	}
}



