package sysctl

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	cfg "cfm/internal/config"
	"cfm/internal/managedsysctl"
)

const persistPath = "/etc/sysctl.d/99-cfm.conf"

func ApplyTweaks(c *cfg.SystemTweaksConfig) error {
	if c == nil || !c.Enable {
		return nil
	}
	// Defaults guard (σε περίπτωση που δεν έχεις καλέσει setDefaults νωρίτερα)
	c.SetDefaults()

	// 1) Conntrack sizing από RAM
	memGB, _ := readMemGB()
	targetCT := clamp(memGB*c.CTPerGB, c.CTMin, c.CTMax)

	// 2) Φτιάξε key→value pairs για runtime write
	kv := sysctlKeyValueMap(c, targetCT)
	pairs := kvMapToManagedPairs(kv)

	// 3) Apply live. managedsysctl.ApplyKeys is deliberately
	// continue-on-error: a missing kernel/module key should be visible to
	// operators, but must not stop later keys or daemon startup.
	res := managedsysctl.ApplyKeys(pairs)
	if err := res.Err(); err != nil {
		fmt.Fprintf(os.Stderr, "%v\n", err)
	}

	// 3a) Προσπάθησε να ρυθμίσεις hashsize (όπου επιτρέπεται)
	trySetHashsize(targetCT / 4) // best-effort

	// 4) Persist (αν ζητηθεί)
	if c.Persist {
		if err := persistSysctlFile(pairs); err != nil {
			return fmt.Errorf("persist sysctl file: %w", err)
		}
	}
	return nil
}

func sysctlKeyValueMap(c *cfg.SystemTweaksConfig, targetCT int) map[string]string {
	kv := map[string]string{
		// Conntrack
		"net.netfilter.nf_conntrack_max": itoa(targetCT),
		// Strictness / timeouts
		"net.ipv4.tcp_syn_retries":                          itoa(c.TCPSynRetries),
		"net.ipv4.tcp_synack_retries":                       itoa(c.TCPSynAckRetries),
		"net.ipv4.tcp_fin_timeout":                          itoa(c.TCPFinTimeout),
		"net.netfilter.nf_conntrack_tcp_timeout_time_wait":  itoa(c.CTTimeWait),
		"net.netfilter.nf_conntrack_tcp_timeout_fin_wait":   itoa(c.CTFinWait),
		"net.netfilter.nf_conntrack_tcp_timeout_close_wait": itoa(c.CTCloseWait),
		// Hygiene
		"net.ipv4.conf.all.rp_filter":        itoa(c.RPFilter),
		"net.ipv4.conf.all.accept_redirects": bool01(c.AcceptRedirects),
		"net.ipv4.conf.all.send_redirects":   bool01(c.SendRedirects),

		"net.ipv4.conf.default.rp_filter":        itoa(c.RPFilter),
		"net.ipv4.conf.default.accept_redirects": bool01(c.AcceptRedirects),
		"net.ipv4.conf.default.send_redirects":   bool01(c.SendRedirects),

		// IPv6 hygiene (safe defaults)
		"net.ipv6.conf.all.accept_redirects":     "0",
		"net.ipv6.conf.all.send_redirects":       "0",
		"net.ipv6.conf.default.accept_redirects": "0",
		"net.ipv6.conf.default.send_redirects":   "0",

		// Needed for DNAT -> 127.0.0.1 (challenge loopback listeners)
		// Default ON (when SYS_TWEAKS_ENABLE=1)
		"net.ipv4.conf.all.route_localnet":     "1",
		"net.ipv4.conf.default.route_localnet": "1",

		// Safety net (συμπληρωματικό)
		"net.ipv4.tcp_syncookies": "1",
	}

	// nf_conntrack_tcp_loose -> 0 όταν strict
	if c.TCPLooseStrict {
		kv["net.netfilter.nf_conntrack_tcp_loose"] = "0"
	}
	return kv
}

func kvMapToManagedPairs(kv map[string]string) []managedsysctl.KeyValuePair {
	if len(kv) == 0 {
		return nil
	}
	pairs := make([]managedsysctl.KeyValuePair, 0, len(kv))
	seen := make(map[string]struct{}, len(kv))
	for _, k := range managedKeys {
		if v, ok := kv[k]; ok {
			pairs = append(pairs, managedsysctl.KeyValuePair{Key: k, Value: v})
			seen[k] = struct{}{}
		}
	}
	if len(seen) == len(kv) {
		return pairs
	}
	// Stable fallback for any future computed key not yet added to managedKeys.
	extra := make([]string, 0, len(kv)-len(seen))
	for k := range kv {
		if _, ok := seen[k]; !ok {
			extra = append(extra, k)
		}
	}
	sort.Strings(extra)
	for _, k := range extra {
		pairs = append(pairs, managedsysctl.KeyValuePair{Key: k, Value: kv[k]})
	}
	return pairs
}

func readMemGB() (int, error) {
	f, err := os.Open("/proc/meminfo")
	if err != nil {
		return 0, err
	}
	defer f.Close()

	var kb int64
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line := sc.Text()
		if strings.HasPrefix(line, "MemTotal:") {
			fields := strings.Fields(line)
			if len(fields) >= 2 {
				// MemTotal σε kB
				kb, _ = strconv.ParseInt(fields[1], 10, 64)
				break
			}
		}
	}
	if kb <= 0 {
		return 0, errors.New("cannot read MemTotal")
	}
	gb := int((kb + (1024*1024 - 1)) / (1024 * 1024)) // round-up to GB
	if gb <= 0 {
		gb = 1
	}
	return gb, nil
}

func clamp(v, lo, hi int) int {
	if v < lo {
		return lo
	}
	if v > hi {
		return hi
	}
	return v
}

func bool01(b bool) string {
	if b {
		return "1"
	}
	return "0"
}

func itoa(i int) string { return strconv.Itoa(i) }

func persistSysctlFile(pairs []managedsysctl.KeyValuePair) error {
	return persistSysctlFileTo(persistPath, pairs)
}

func persistSysctlFileTo(path string, pairs []managedsysctl.KeyValuePair) error {
	values := make(map[string]string, len(pairs))
	for _, p := range pairs {
		values[p.Key] = p.Value
	}

	var b strings.Builder
	b.WriteString("# Generated by CFM - DO NOT EDIT\n")
	b.WriteString("# Apply at boot via systemd-sysctl.\n")
	// Για σταθερότητα, γράψε τα κλειδιά με “γνωστή” σειρά.
	// Γράψε μόνο όσα υπήρχαν στο computed pair set.
	written := make(map[string]struct{}, len(values))
	for _, k := range managedKeys {
		if v, ok := values[k]; ok {
			fmt.Fprintf(&b, "%s = %s\n", k, v)
			written[k] = struct{}{}
		}
	}
	if len(written) < len(values) {
		// Future-proof deterministic output for computed keys not yet part of
		// the static ownership list.
		extra := make([]string, 0, len(values)-len(written))
		for k := range values {
			if _, ok := written[k]; !ok {
				extra = append(extra, k)
			}
		}
		sort.Strings(extra)
		for _, k := range extra {
			fmt.Fprintf(&b, "%s = %s\n", k, values[k])
		}
	}
	return atomicWriteFile(path, []byte(b.String()), 0600)
}

func atomicWriteFile(path string, content []byte, mode os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("mkdir %s: %w", dir, err)
	}
	f, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-")
	if err != nil {
		return fmt.Errorf("create tmp: %w", err)
	}
	tmpPath := f.Name()
	defer func() {
		_ = os.Remove(tmpPath)
	}()

	if _, err := f.Write(content); err != nil {
		_ = f.Close()
		return fmt.Errorf("write %s: %w", tmpPath, err)
	}
	if err := f.Sync(); err != nil {
		_ = f.Close()
		return fmt.Errorf("fsync %s: %w", tmpPath, err)
	}
	if err := f.Chmod(mode); err != nil {
		_ = f.Close()
		return fmt.Errorf("chmod %s: %w", tmpPath, err)
	}
	if err := f.Close(); err != nil {
		return fmt.Errorf("close %s: %w", tmpPath, err)
	}
	if err := os.Rename(tmpPath, path); err != nil {
		return fmt.Errorf("rename %s -> %s: %w", tmpPath, path, err)
	}
	return nil
}

// Best-effort set hashsize (τρέχει μόνο αν υπάρχει parameter file)
func trySetHashsize(v int) {
	if v <= 0 {
		return
	}
	path := "/sys/module/nf_conntrack/parameters/hashsize"
	// Αν δεν υπάρχει, το kernel δεν επιτρέπει runtime write (χρειάζεται modprobe param).
	// Δεν θεωρείται σφάλμα.
	if _, err := os.Stat(path); err == nil {
		_ = os.WriteFile(path, []byte(itoa(v)), 0600)
	}
}
