[global]
DEFAULT_EVERY   = "60s"
DEFAULT_TIMEOUT = "8s"
DEFAULT_COOLDOWN = "10m"

[exim_queues]
ENABLED          = 1
EVERY            = "60s"
TIMEOUT          = "8s"
QUEUE_TOTAL_MAX  = 300
QUEUE_FROZEN_MAX = 100
SAMPLE_LIMIT     = 10
COOLDOWN         = "10m"



[exim_relays]
ENABLED = 1
LOG_PATH = "" ;empty for autodetect
WINDOW = "15m"
EVERY  = "5s"
SAMPLE_LIMIT = 10
COOLDOWN = "10m"

; thresholds (>=)
LOCAL_USER_MAX   = 110
AUTH_USER_MAX    = 110
AUTH_IP_MAX      = 110
AUTH_USERIP_MAX  = 120
UNAUTH_IP_MAX    = 250

; enrichment
ENRICH      = 1
PTR         = 1
ENRICH_DIRS = "/etc/cfm, /usr/share/GeoIP, ./configs"



[exim_security]
ENABLED = 1
LOG_PATH     = ""
EVERY        = "2s"
WINDOW       = "15m"
SAMPLE_LIMIT = 10
COOLDOWN     = "20m"
RULES        = "/etc/cfm/exim_security.rules"

; enrichment
ENRICH      = 1
PTR         = 1
ENRICH_DIRS = "/etc/cfm, /usr/share/GeoIP"


[ssh_auth]
ENABLED = 1
; mode is journal (systemd) or file
;MODE = journal
;JOURNAL_UNIT = sshd.service
MODE = file
LOG_PATH = "/var/log/secure"
EVERY = "2s"
WINDOW = "15m"
SAMPLE_LIMIT = 10
COOLDOWN = "20m"

; thresholds - different per user and IP. useful for distributed attacks
AUTHFAIL_IP = 20
AUTHFAIL_USER = 10
DDOS_IP = 30

; enrichment
ENRICH = 1
PTR = 1
ENRICH_DIRS = "/etc/cfm, /usr/share/GeoIP"
