[global]
DEFAULT_EVERY   = "60s"
DEFAULT_TIMEOUT = "8s"
DEFAULT_COOLDOWN = "10m"

[exim_queues]
ENABLED          = 1
EVERY            = "60s"
TIMEOUT          = "8s"
QUEUE_TOTAL_MAX  = 300
QUEUE_FROZEN_MAX = 100
SAMPLE_LIMIT     = 10
COOLDOWN         = "10m"



[exim_relays]
ENABLED = 1
LOG_PATH = "" ;empty for autodetect
WINDOW = "15m"
EVERY  = "5s"
SAMPLE_LIMIT = 10
COOLDOWN = "10m"

; thresholds (>=)
LOCAL_USER_MAX   = 90
AUTH_USER_MAX    = 90
AUTH_IP_MAX      = 90
AUTH_USERIP_MAX  = 90
UNAUTH_IP_MAX    = 10

; enrichment
ENRICH      = 1
PTR         = 1
ENRICH_DIRS = "/etc/cfm, /usr/share/GeoIP, ./configs"
