# /etc/nginx/conf.d/cfm-nginx.conf

map $http_x_real_ip $cfm_client_ip {
    default $http_x_real_ip;
    ""      $remote_addr;
}

log_format cfm_tsv escape=none
    '$msec\t$cfm_client_ip\t$host\t$request_method\t$request_uri\t$server_protocol\t'
    '$status\t$body_bytes_sent\t$request_time\t$upstream_response_time\t'
    '$http_referer\t$http_user_agent';

