// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadCfmlsm returns the embedded CollectionSpec for cfmlsm.
func loadCfmlsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CfmlsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cfmlsm: %w", err)
	}

	return spec, err
}

// loadCfmlsmObjects loads cfmlsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cfmlsmObjects
//	*cfmlsmPrograms
//	*cfmlsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCfmlsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCfmlsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cfmlsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmSpecs struct {
	cfmlsmProgramSpecs
	cfmlsmMapSpecs
	cfmlsmVariableSpecs
}

// cfmlsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmProgramSpecs struct {
	CfmMemfdExec *ebpf.ProgramSpec `ebpf:"cfm_memfd_exec"`
}

// cfmlsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmMapSpecs struct {
	CfmEvents *ebpf.MapSpec `ebpf:"cfm_events"`
}

// cfmlsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmVariableSpecs struct {
}

// cfmlsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmObjects struct {
	cfmlsmPrograms
	cfmlsmMaps
	cfmlsmVariables
}

func (o *cfmlsmObjects) Close() error {
	return _CfmlsmClose(
		&o.cfmlsmPrograms,
		&o.cfmlsmMaps,
	)
}

// cfmlsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmMaps struct {
	CfmEvents *ebpf.Map `ebpf:"cfm_events"`
}

func (m *cfmlsmMaps) Close() error {
	return _CfmlsmClose(
		m.CfmEvents,
	)
}

// cfmlsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmVariables struct {
}

// cfmlsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmPrograms struct {
	CfmMemfdExec *ebpf.Program `ebpf:"cfm_memfd_exec"`
}

func (p *cfmlsmPrograms) Close() error {
	return _CfmlsmClose(
		p.CfmMemfdExec,
	)
}

func _CfmlsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cfmlsm_arm64_bpfel.o
var _CfmlsmBytes []byte
