// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64

package lsm

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type cfmlsmCfmCredTransitionState struct {
	_                 structs.HostLayout
	TaskFixSetuidCred uint64
}

type cfmlsmCfmInodeKey struct {
	_   structs.HostLayout
	Dev uint64
	Ino uint64
}

type cfmlsmCfmWebOriginState struct {
	_         structs.HostLayout
	WebOrigin uint8
}

// loadCfmlsm returns the embedded CollectionSpec for cfmlsm.
func loadCfmlsm() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_CfmlsmBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load cfmlsm: %w", err)
	}

	return spec, err
}

// loadCfmlsmObjects loads cfmlsm and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*cfmlsmObjects
//	*cfmlsmPrograms
//	*cfmlsmMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadCfmlsmObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadCfmlsm()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// cfmlsmSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmSpecs struct {
	cfmlsmProgramSpecs
	cfmlsmMapSpecs
	cfmlsmVariableSpecs
}

// cfmlsmProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmProgramSpecs struct {
	CfmBpf001               *ebpf.ProgramSpec `ebpf:"cfm_bpf001"`
	CfmCred002              *ebpf.ProgramSpec `ebpf:"cfm_cred002"`
	CfmCred003              *ebpf.ProgramSpec `ebpf:"cfm_cred003"`
	CfmDeletedFileExec      *ebpf.ProgramSpec `ebpf:"cfm_deleted_file_exec"`
	CfmEphemeralExec        *ebpf.ProgramSpec `ebpf:"cfm_ephemeral_exec"`
	CfmExec007Finit         *ebpf.ProgramSpec `ebpf:"cfm_exec007_finit"`
	CfmExec007Init          *ebpf.ProgramSpec `ebpf:"cfm_exec007_init"`
	CfmFs005Create          *ebpf.ProgramSpec `ebpf:"cfm_fs005_create"`
	CfmFs005Link            *ebpf.ProgramSpec `ebpf:"cfm_fs005_link"`
	CfmFs005MarkExec        *ebpf.ProgramSpec `ebpf:"cfm_fs005_mark_exec"`
	CfmFs005MarkSetuid      *ebpf.ProgramSpec `ebpf:"cfm_fs005_mark_setuid"`
	CfmFs005MarkTaskAlloc   *ebpf.ProgramSpec `ebpf:"cfm_fs005_mark_task_alloc"`
	CfmFs005Rename          *ebpf.ProgramSpec `ebpf:"cfm_fs005_rename"`
	CfmFs005SetattrIdmap    *ebpf.ProgramSpec `ebpf:"cfm_fs005_setattr_idmap"`
	CfmFs005SetattrNoidmap  *ebpf.ProgramSpec `ebpf:"cfm_fs005_setattr_noidmap"`
	CfmFs005SetxattrIdmap   *ebpf.ProgramSpec `ebpf:"cfm_fs005_setxattr_idmap"`
	CfmFs005SetxattrNoidmap *ebpf.ProgramSpec `ebpf:"cfm_fs005_setxattr_noidmap"`
	CfmFs005Unlink          *ebpf.ProgramSpec `ebpf:"cfm_fs005_unlink"`
	CfmFs006                *ebpf.ProgramSpec `ebpf:"cfm_fs006"`
	CfmFs007SetattrIdmap    *ebpf.ProgramSpec `ebpf:"cfm_fs007_setattr_idmap"`
	CfmFs007SetattrNoidmap  *ebpf.ProgramSpec `ebpf:"cfm_fs007_setattr_noidmap"`
	CfmFs007SetxattrIdmap   *ebpf.ProgramSpec `ebpf:"cfm_fs007_setxattr_idmap"`
	CfmFs007SetxattrNoidmap *ebpf.ProgramSpec `ebpf:"cfm_fs007_setxattr_noidmap"`
	CfmInterpNetStdio       *ebpf.ProgramSpec `ebpf:"cfm_interp_net_stdio"`
	CfmMemfdExec            *ebpf.ProgramSpec `ebpf:"cfm_memfd_exec"`
	CfmRevshell             *ebpf.ProgramSpec `ebpf:"cfm_revshell"`
}

// cfmlsmMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmMapSpecs struct {
	CfmCredTransitionTasks *ebpf.MapSpec `ebpf:"cfm_cred_transition_tasks"`
	CfmEvents              *ebpf.MapSpec `ebpf:"cfm_events"`
	CfmSetuidInodes        *ebpf.MapSpec `ebpf:"cfm_setuid_inodes"`
	CfmWatchedInodes       *ebpf.MapSpec `ebpf:"cfm_watched_inodes"`
	CfmWatchedUids         *ebpf.MapSpec `ebpf:"cfm_watched_uids"`
	CfmWebOriginTasks      *ebpf.MapSpec `ebpf:"cfm_web_origin_tasks"`
}

// cfmlsmVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type cfmlsmVariableSpecs struct {
	CfmEnforceDeletedFileExec *ebpf.VariableSpec `ebpf:"cfm_enforce_deleted_file_exec"`
	CfmEnforceEphemeralExec   *ebpf.VariableSpec `ebpf:"cfm_enforce_ephemeral_exec"`
	CfmEnforceMemfdExec       *ebpf.VariableSpec `ebpf:"cfm_enforce_memfd_exec"`
	CfmEnforcePrivInstall     *ebpf.VariableSpec `ebpf:"cfm_enforce_priv_install"`
	CfmEnforceRevshell        *ebpf.VariableSpec `ebpf:"cfm_enforce_revshell"`
	CfmEnforceSensitiveWrite  *ebpf.VariableSpec `ebpf:"cfm_enforce_sensitive_write"`
	CfmFs005WebOriginMonitor  *ebpf.VariableSpec `ebpf:"cfm_fs005_web_origin_monitor"`
}

// cfmlsmObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmObjects struct {
	cfmlsmPrograms
	cfmlsmMaps
	cfmlsmVariables
}

func (o *cfmlsmObjects) Close() error {
	return _CfmlsmClose(
		&o.cfmlsmPrograms,
		&o.cfmlsmMaps,
	)
}

// cfmlsmMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmMaps struct {
	CfmCredTransitionTasks *ebpf.Map `ebpf:"cfm_cred_transition_tasks"`
	CfmEvents              *ebpf.Map `ebpf:"cfm_events"`
	CfmSetuidInodes        *ebpf.Map `ebpf:"cfm_setuid_inodes"`
	CfmWatchedInodes       *ebpf.Map `ebpf:"cfm_watched_inodes"`
	CfmWatchedUids         *ebpf.Map `ebpf:"cfm_watched_uids"`
	CfmWebOriginTasks      *ebpf.Map `ebpf:"cfm_web_origin_tasks"`
}

func (m *cfmlsmMaps) Close() error {
	return _CfmlsmClose(
		m.CfmCredTransitionTasks,
		m.CfmEvents,
		m.CfmSetuidInodes,
		m.CfmWatchedInodes,
		m.CfmWatchedUids,
		m.CfmWebOriginTasks,
	)
}

// cfmlsmVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmVariables struct {
	CfmEnforceDeletedFileExec *ebpf.Variable `ebpf:"cfm_enforce_deleted_file_exec"`
	CfmEnforceEphemeralExec   *ebpf.Variable `ebpf:"cfm_enforce_ephemeral_exec"`
	CfmEnforceMemfdExec       *ebpf.Variable `ebpf:"cfm_enforce_memfd_exec"`
	CfmEnforcePrivInstall     *ebpf.Variable `ebpf:"cfm_enforce_priv_install"`
	CfmEnforceRevshell        *ebpf.Variable `ebpf:"cfm_enforce_revshell"`
	CfmEnforceSensitiveWrite  *ebpf.Variable `ebpf:"cfm_enforce_sensitive_write"`
	CfmFs005WebOriginMonitor  *ebpf.Variable `ebpf:"cfm_fs005_web_origin_monitor"`
}

// cfmlsmPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadCfmlsmObjects or ebpf.CollectionSpec.LoadAndAssign.
type cfmlsmPrograms struct {
	CfmBpf001               *ebpf.Program `ebpf:"cfm_bpf001"`
	CfmCred002              *ebpf.Program `ebpf:"cfm_cred002"`
	CfmCred003              *ebpf.Program `ebpf:"cfm_cred003"`
	CfmDeletedFileExec      *ebpf.Program `ebpf:"cfm_deleted_file_exec"`
	CfmEphemeralExec        *ebpf.Program `ebpf:"cfm_ephemeral_exec"`
	CfmExec007Finit         *ebpf.Program `ebpf:"cfm_exec007_finit"`
	CfmExec007Init          *ebpf.Program `ebpf:"cfm_exec007_init"`
	CfmFs005Create          *ebpf.Program `ebpf:"cfm_fs005_create"`
	CfmFs005Link            *ebpf.Program `ebpf:"cfm_fs005_link"`
	CfmFs005MarkExec        *ebpf.Program `ebpf:"cfm_fs005_mark_exec"`
	CfmFs005MarkSetuid      *ebpf.Program `ebpf:"cfm_fs005_mark_setuid"`
	CfmFs005MarkTaskAlloc   *ebpf.Program `ebpf:"cfm_fs005_mark_task_alloc"`
	CfmFs005Rename          *ebpf.Program `ebpf:"cfm_fs005_rename"`
	CfmFs005SetattrIdmap    *ebpf.Program `ebpf:"cfm_fs005_setattr_idmap"`
	CfmFs005SetattrNoidmap  *ebpf.Program `ebpf:"cfm_fs005_setattr_noidmap"`
	CfmFs005SetxattrIdmap   *ebpf.Program `ebpf:"cfm_fs005_setxattr_idmap"`
	CfmFs005SetxattrNoidmap *ebpf.Program `ebpf:"cfm_fs005_setxattr_noidmap"`
	CfmFs005Unlink          *ebpf.Program `ebpf:"cfm_fs005_unlink"`
	CfmFs006                *ebpf.Program `ebpf:"cfm_fs006"`
	CfmFs007SetattrIdmap    *ebpf.Program `ebpf:"cfm_fs007_setattr_idmap"`
	CfmFs007SetattrNoidmap  *ebpf.Program `ebpf:"cfm_fs007_setattr_noidmap"`
	CfmFs007SetxattrIdmap   *ebpf.Program `ebpf:"cfm_fs007_setxattr_idmap"`
	CfmFs007SetxattrNoidmap *ebpf.Program `ebpf:"cfm_fs007_setxattr_noidmap"`
	CfmInterpNetStdio       *ebpf.Program `ebpf:"cfm_interp_net_stdio"`
	CfmMemfdExec            *ebpf.Program `ebpf:"cfm_memfd_exec"`
	CfmRevshell             *ebpf.Program `ebpf:"cfm_revshell"`
}

func (p *cfmlsmPrograms) Close() error {
	return _CfmlsmClose(
		p.CfmBpf001,
		p.CfmCred002,
		p.CfmCred003,
		p.CfmDeletedFileExec,
		p.CfmEphemeralExec,
		p.CfmExec007Finit,
		p.CfmExec007Init,
		p.CfmFs005Create,
		p.CfmFs005Link,
		p.CfmFs005MarkExec,
		p.CfmFs005MarkSetuid,
		p.CfmFs005MarkTaskAlloc,
		p.CfmFs005Rename,
		p.CfmFs005SetattrIdmap,
		p.CfmFs005SetattrNoidmap,
		p.CfmFs005SetxattrIdmap,
		p.CfmFs005SetxattrNoidmap,
		p.CfmFs005Unlink,
		p.CfmFs006,
		p.CfmFs007SetattrIdmap,
		p.CfmFs007SetattrNoidmap,
		p.CfmFs007SetxattrIdmap,
		p.CfmFs007SetxattrNoidmap,
		p.CfmInterpNetStdio,
		p.CfmMemfdExec,
		p.CfmRevshell,
	)
}

func _CfmlsmClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed cfmlsm_arm64_bpfel.o
var _CfmlsmBytes []byte
